### ISSUE TITLE
Blinky?

### ISSUE THREAD

**Issue by AdySan** [sandeepmistry/arduino-nRF5#1]
Just got this setup according to the ReadMe. Based on the following output seems to be building and downloading ok. For a simple Blink.ino example, what PIN should I use? 13 doesnt seem to work, not sure how these nrf52 pins are mapped.

```
GNU ARM Eclipse 64-bits Open On-Chip Debugger 0.10.0-dev-00287-g85cec24 (2016-01-10-12:03)
Licensed under GNU GPL v2
For bug reports, read
	http://openocd.org/doc/doxygen/bugs.html
debug_level: 0
swd
cortex_m reset_config sysresetreq
adapter speed: 1000 kHz
nrf51.cpu: target state: halted
target halted due to debug-request, current mode: Thread 
xPSR: 0x01000000 pc: 0x00000574 msp: 0x20008000
** Programming Started **
auto erase enabled
wrote 4096 bytes from file /var/folders/75/wvhmv78s3zz48zf4fssk4__40000gn/T/buildd5ae82e677127ac286f51de66781d807.tmp/Blink.ino.bin in 0.232602s (17.197 KiB/s)
** Programming Finished **
** Verify Started **
verified 3388 bytes in 0.085533s (38.682 KiB/s)
** Verified OK **
** Resetting Target **
shutdown command invoked
```

**Comment by AdySan** [comment]
These don't work btw.

```
// LEDs
#define PIN_LED1                (17)
#define PIN_LED2                (18)
#define PIN_LED3                (19)
#define PIN_LED4                (20)
#define LED_BUILTIN             PIN_LED1
```

**Comment by AdySan** [comment]
FWIW, the example hex files located here from SDK 11.0 work fine, so hardware is ok.
```
/Users/adityatannu/Developer/nRF5_SDK_11.0.0_89a8197\ /examples/peripheral/blinky/hex 
```

**Comment by sandeepmistry** [comment]
@AdySan check the back of the board, they are are actually connected to P0.17-20 which map to Arduino pin connectors D6-D9.

**Comment by AdySan** [comment]
Yes, will test soon 
![file mar 30 4 51 19 pm](https://cloud.githubusercontent.com/assets/744810/14161352/ba381f64-f697-11e5-96ae-f3f8b64b7ed8.jpeg)

**Comment by AdySan** [comment]
How do I work on the latest core? Looks like I'm not getting the latest changes from the core by placing it in `hardware/nRF5` and updating it via git. I've also installed using Boards Manager. Do I need to rebuild the core somehow?
