### ISSUE TITLE
Warnings for library classes: Wire and SPI 

### ISSUE THREAD

**Issue by bojh** [sandeepmistry/arduino-nRF5#10]
Compiling an sketch does create following warnings:

```
WARNING: library SPI claims to run on [nRF5] architecture(s) and may be incompatible with your current board which runs on [nRF] architecture(s).
WARNING: library Wire claims to run on [nRF5] architecture(s) and may be incompatible with your current board which runs on [nRF] architecture(s).
```
There must be a mismatch in between a architcture naming `nRF` and the `nRF5`.

**Comment by sandeepmistry** [comment]
@bojh could you please share all of the build output?

Maybe you core is in a ``nRF`` folder instead of ``nRF5``?

**Comment by bojh** [comment]
You a right - thanks at all. My folder is the `nRF` one - and I know than why I got 2 Nordic board groups in the board selection of the manager menu :-) But this is not so bad for to switch over between the developer and manager core version.
