### ISSUE TITLE
Tiny BLE soft device errors

### ISSUE THREAD

**Issue by tsong08** [sandeepmistry/arduino-nRF5#102]
A common error we keep seeing is:

```
fatal error: ble_gatts.h: No such file or directory

compilation terminated.
```

If you see this error, the solution is to go to tools>softdevices>select softdevice.

Include in FAQ for future reference?

#HackIllinois2017

**Comment by dlabun** [comment]
Thanks for the suggestion. I assume this is occurring when using the BLE Peripheral library?

**Comment by sandeepmistry** [comment]
@tsong08 yes please, PR to the read me would be great.

**Comment by tsong08** [comment]
@dlabun Yes this is specific to the BLE Peripheral code. Basic sketches compile fine.

**Comment by dlabun** [comment]
@sandeepmistry Should the note be here, on the BLE-Peripheral library or both?

**Comment by sandeepmistry** [comment]
There's a note here: https://github.com/sandeepmistry/arduino-nRF5#ble

However, maybe it needs to be clearer. We can also update the BLEPeripheral read me.

**Comment by dlabun** [comment]
Maybe something along the lines of "trying to use the BLEPeripherial library without selecting a Soft Device in the menu will result in build errors"?

**Comment by jacobrosenthal** [comment]
Yeah I think its just a 'bad' error message, presuming we cant detect and
generate a better one instead, itd be good to document specifically that
this error should be translated as 'please select a softdevice'
```

fatal error: ble_gatts.h: No such file or directory

```

**Comment by sandeepmistry** [comment]
@jacobrosenthal @dlabun those sound like good ideas, any ones have time to prep a PR?

**Comment by jacobrosenthal** [comment]
Can close this for https://github.com/sandeepmistry/arduino-BLEPeripheral/pull/129
