### ISSUE TITLE
How can I configure an interruption?

### ISSUE THREAD

**Issue by XaviLC** [sandeepmistry/arduino-nRF5#120]
Hello all,

I was wondering, can I make use of the interruptions for the nrf52 dk? 

 I would like to attach some sensor(accelerometer) into my board and I would like to configure that it can interrupt if there is a movement, basic stuff; the library that I am using for it doesn't have implemented the interruption itself so I will have to code it for the nrf52, is ther any example that I might use? 

Thank in advance,

regards!

**Comment by carlosperate** [comment]
The `attachInterrupt` arduino function (https://www.arduino.cc/en/Reference/attachInterrupt) is already implemented in `cores/nRF5/WInterrupts.h/.c`.

**Comment by sandeepmistry** [comment]
@carlosperate thanks for helping out!

@XaviLC please see the answer above.
