### ISSUE TITLE
Preferred way to add nRF52 libraries to the SDK

### ISSUE THREAD

**Issue by nestorsilk** [sandeepmistry/arduino-nRF5#122]
Recently I've started to extend the SDK with additional nRF52 libraries like the crypto lib. 
Did try the following ways:

1. added a "libraries" folder to the /SDK/components path containing the crypto lib
2 added crypto lib to the SDK/components/drivers_nrf path like it is done for delay 
3. tried some other places.

None of them worked. So, decided to go for the conventional road adding to crypt lib to the overall  libraries folder of the nRF52 board package. This works well, but it is very tricky then to handle all the dependencies to device- , util- and driver_nrf files. 

This leads to my question: " What is the preferred way to extend the nRF52 board package's SDK?".

Tom

**Comment by sandeepmistry** [comment]
Hey @nestorsilk,

Unfortunately, the license for the `components/drivers_nrf/*` files and most of the Nordic SDK is not friendly. Here's a snippet from the I2S header:

```
/* Copyright (c) 2015 Nordic Semiconductor. All Rights Reserved.
 *
 * The information contained herein is property of Nordic Semiconductor ASA.
 * Terms and conditions of usage are described in detail in NORDIC
 * SEMICONDUCTOR STANDARD SOFTWARE LICENSE AGREEMENT.
 *
 * Licensees are granted free, non-transferable use of the information. NO
 * WARRANTY of ANY KIND is provided. This heading must NOT be removed from
 * the file.
 *
 */
```

>  " What is the preferred way to extend the nRF52 board package's SDK?".

Unless we can find a friendlier license for the files, the best approach is to use the registers directly:

 * https://github.com/sandeepmistry/arduino-nRF5/blob/master/cores/nRF5/SDK/components/device/nrf51.h
 * https://github.com/sandeepmistry/arduino-nRF5/blob/master/cores/nRF5/SDK/components/device/nrf52.h


Closing this as answered for now. However, we can continue the discussion here and re-open if needed.
