### ISSUE TITLE
nRF52832 sketch repository

### ISSUE THREAD

**Issue by kriswiner** [sandeepmistry/arduino-nRF5#124]
Thank you Sandeep for providing this Arduino Core and the BLEPeripheral. I have figured out how to get these to work with my custom nRF52 devices and I have started to populate a repository with well-commented examples of how to make use of them. I hope others benefit from the examples. They can be found here:

https://github.com/kriswiner/nRF52832DevBoard

I'll be adding more in the next few weeks.

**Comment by dlabun** [comment]
Kris, If you'd like, do a PR on the Readme to add a link to your examples.

**Comment by kriswiner** [comment]
I'd like to but I am not quite sure how that works.
