### ISSUE TITLE
Version control conflict while flashing soft device

### ISSUE THREAD

**Issue by dattasaurabh82** [sandeepmistry/arduino-nRF5#13]
While flashing the soft-device as per the repo [here](https://github.com/nihaopaul/arduino-nRF5#flashing-a-softdevice) with the [jar file](https://github.com/sandeepmistry/arduino-nRF5/releases/download/tools/nRF5FlashSoftDevice.jar), there happens to be a version conflict between the generated hex file and downloaded one in the path: `$../Arduino15/packages/sandeepmistry/hardware/nRF5/0.1.0/cores/nRF5/SDK/components/softdevice/s132/hex/s132_nrf52_2.0.0_softdevice.hex` . (beteen .._nrf52_2.0.0 & .._nrf52_2.0.1).

**Comment by sandeepmistry** [comment]
Closed via https://github.com/sandeepmistry/arduino-nRF5/pull/12/commits/9b8f3df3c1a0cbf5ba175a230df84c01372f932d from #12.

This fix will be integrated in the next release of the core.
