### ISSUE TITLE
genneric nrf52832 i2c

### ISSUE THREAD

**Issue by reapqin** [sandeepmistry/arduino-nRF5#154]
@kriswiner i am working with nrf52832 + mpu9250 also. And i see your [commet](https://github.com/sandeepmistry/arduino-nRF5/issues/108) about the "I switched to the nRF51Wire.h and everything works"
could you tell me how to switch that? I am begginer wish your help.

i am using a genneric [nrf52832](https://item.taobao.com/item.htm?spm=a230r.1.14.74.IuClmR&id=532630623264&ns=1&abbucket=15#detail)  with all pins out around borad and named by original pin name on chip datasheet. and i changed the sda to 26u scl to 27u in variant.h in genneric fold
and i found the board pins 26 27 was not pullup with resistors. i don't have 4k7 resistors so i use 5k1 resistors instead. is it neccesory?
Wish your help thank you.

**Comment by kriswiner** [comment]
Yes, you need pullups either on your nRF52 board or MPU9250 breakout.

**Comment by reapqin** [comment]
And then ?  how  to  switch  to  nrf51wire.h? thank you.

**Comment by carlosperate** [comment]
The 13 KOhm internal pull ups could be enabled for the I2C pins (they are within this Wire library), so technically speaking external pull ups could not be required.

**Comment by kriswiner** [comment]
You'll have to test this; i use 4K7 pullups.

**Comment by reapqin** [comment]
@kriswiner  ok,  i find 4k7 resistor  and pulled  up. what's next?  thanks ₍ↂ⃙⃙⃚⃛_ↂ⃙⃙⃚⃛₎

**Comment by kriswiner** [comment]
run the code

**Comment by reapqin** [comment]
@kriswiner  it's  not  work.

**Comment by kriswiner** [comment]
open an issue

**Comment by reapqin** [comment]
I test that. it is not neccesory to pullup.

**Comment by dlabun** [comment]
Closing as resolved (?)
