### ISSUE TITLE
WDT (watch dog timer interrupt function)

### ISSUE THREAD

**Issue by cheeta1** [sandeepmistry/arduino-nRF5#157]
hi,
i was wondering i this core has WDT functionality implemented or not.  my code sometimes stucks when reading mpu 6050 and i want to reset it when it stucks. kindly let me know if you have implemented WDT or how can i set it up using code

**Comment by sandeepmistry** [comment]
@cheeta1 please see: https://github.com/sandeepmistry/arduino-nRF5/issues/121#issuecomment-289117544

Also, in the future, please look at existing closed issues prior to opening a new one.
