### ISSUE TITLE
how to avoid softdevice interrupts during i2c read operation

### ISSUE THREAD

**Issue by cheeta1** [sandeepmistry/arduino-nRF5#160]
hi, i am reading mpu6050 with nrf51822. every now and then the data got corrupt because of softDevice interrupts. if i don't use Softdevice the it runs perfectly but when i use softdevice it give me some corrupt data and at times it got stuck at some point. how can i avoid this. 

thanks

**Comment by dlabun** [comment]
Duplicate of #159
