### ISSUE TITLE
support for the nRF52 Blend v2

### ISSUE THREAD

**Issue by gesaleh** [sandeepmistry/arduino-nRF5#178]
Hi
does this library support the new device from RedBear ? blend 2 nano2 ?
I find your work very important and make it easy to have peripheral devices.
Thanks

**Comment by gesaleh** [comment]
ok it wasn't that the issue it is the TimerOne lib issue
I can't compile it I'm getting an error al the time
`temp_sensor:140: error: 'class TimerOne' has no member named 'initialize'

   Timer1.initialize(2 * 1000000); // in milliseconds

          ^

temp_sensor:141: error: 'class TimerOne' has no member named 'attachInterrupt'

   Timer1.attachInterrupt(timerHandler);

          ^

exit status 1
'class TimerOne' has no member named 'initialize'`

**Comment by dlabun** [comment]
Yes, both the Redbear Blend 2 and Nano 2 are supported.

**Comment by sandeepmistry** [comment]
Please see answer here: https://github.com/sandeepmistry/arduino-BLEPeripheral/issues/169#issuecomment-317247667
