### ISSUE TITLE
Custom nRF52 board and L-Link Segger

### ISSUE THREAD

**Issue by clemaitre58** [sandeepmistry/arduino-nRF5#179]
Hi,

I read that we could program a sketch on a cutom mRF52 board by using a J Link hrom the nRF52board aand the code of your repo.

Is it possible to replace the nRF52 by a Segger J-Link like this? https://www.segger.com/products/debug-probes/j-link/models/j-link-edu-mini/

**Comment by jacobrosenthal** [comment]
That should work fine out of the box. Products like that and the segger jlink edu are all just segger jlinks under the hood.

**Comment by sandeepmistry** [comment]
@clemaitre58 please see @jacobrosenthal's response above.

**Comment by sandeepmistry** [comment]
The programmer just needs to work with openocd.
