### ISSUE TITLE
BLESrerial stream libray issue

### ISSUE THREAD

**Issue by cheeta1** [sandeepmistry/arduino-nRF5#181]
BLESerial.parseFloat();
BLESerial.parseInt();
these function are not working properly they only return the value of firts two char that i send eg if i send 1000 it return 10. i have tried to increase timeout to 5 sec but still same results

**Comment by dlabun** [comment]
Are you referring to the BLEPeripherial repository?

**Comment by cheeta1** [comment]
yes sorry i thought i posted it on BLEPeripherial repository

**Comment by dlabun** [comment]
No worries, Please post it over there so it gets the right attention.

**Comment by cheeta1** [comment]
i posted it there thanks.
