### ISSUE TITLE
[Question] Using arduino primo examples with nRF52 DK board

### ISSUE THREAD

**Issue by mitko9000** [sandeepmistry/arduino-nRF5#201]
Hello guys i have two nRF52 DK laying around and I was wondering can I upload an Arduino Primo code to them ?

I can successfully use nRF52 DK with bluetooth peripheral with S132 soft device testing the bluetooth and the blink program

**Comment by dlabun** [comment]
Maybe... The Primo has a service processor on it so as long as you aren't using any of those functions you should be able to use your code on both boards.

**Comment by mitko9000** [comment]
@dlabun Any pointers how to do this easily because I have to somehow transfer primo libraries code to the nrf52 core here ?

Or this is not done yet

**Comment by dlabun** [comment]
It all depends on your code so it's hard for me to say... Right off the bat, anything like the WiFi or IrRD features or the ON, BLE or User2 LEDs can't be used with the nRF52 DK.

**Comment by dmikhalsky** [comment]
I did it. Successufully. 
You have to install Primo board in Arduino IDE and compile for it. Then, it generates a combined "SD + bootloader + code" hex file. You simply drag the file to Segger drive and voila, it works.

**Comment by mitko9000** [comment]
@dmikhalsky How to compile without having the board ?

**Comment by dmikhalsky** [comment]
??? As I said, just install it via the Board manager, choose "Arduino Primo" as your board, load any example and press "Upload"
Of course, you'll get an error, but there will be a generated hex file.

**Comment by mitko9000** [comment]
@dmikhalsky Ok I got that there was a option in the preferences for arduino to show me the compilation path dont have a board right now to try but I will try it ASAP.

Thanks 👍

**Comment by dmikhalsky** [comment]
Cool. If you need Serial (of course, you need :-), you'll also have to change pin definitions in variants.c, but that's another story.

**Comment by mitko9000** [comment]
@dmikhalsky As far as I checked it should be trivial to replace the variants.c with the nrf52 dk kit from here its just simple pinout :)

**Comment by dmikhalsky** [comment]
Didn't work for me, but might work for you
