### ISSUE TITLE
Second Serial Port on Micro:bit ?

### ISSUE THREAD

**Issue by LoRaTracker** [sandeepmistry/arduino-nRF5#203]
First of all congratulatons. 

I have a LoRa (SPI device) based transmitter and receiver, writen originally for Arduino Pro Mini, and it works just fine on the Arduino Microbit. 

I2C stuff works as well, routines I wrote to read\write to an I2C FRAM work well. 

However, is there a way of assigning a second serial port, in addition to the normal serial terminal ?

**Comment by micooke** [comment]
There is only one hardware serial port, and software serial doesn't currently work, but should shortly.

See #98 for details

**Comment by dlabun** [comment]
Closing as resolved
