### ISSUE TITLE
Persistent Storage

### ISSUE THREAD

**Issue by gpgabriel** [sandeepmistry/arduino-nRF5#210]
Hi,

I might be wrong but from the current source code of this repository I think there's no way to use FDS or pstorage as they're not included from the SDK. (https://infocenter.nordicsemi.com/index.jsp?topic=%2Fcom.nordic.infocenter.sdk5.v11.0.0%2Flib_pstorage.html)

Is there any plan to add this functionality?

Gabriel

**Comment by dlabun** [comment]
Correct, PStorage is not included. I do not believe there are any plans currently to add it as it would require relying more on the Nordic SDK.

**Comment by sandeepmistry** [comment]
@gpgabriel checkout's @d00616's library: https://github.com/d00616/arduino-NVM

**Comment by DhirajGehlot** [comment]
Hello @sandeepmistry 

Correct me if I am wrong. According to this link: http://infocenter.nordicsemi.com/index.jsp?topic=/com.nordic.infocenter.s130.sds/dita/softdevices/s130/sd_resource_reqs/hw_block_interrupt_vector.html&cp=3_7_2_0_6_0
if softdevice is enabled, the flash can be written only through SoftDevice API sd_flash_write commands.
https://github.com/d00616/arduino-NVM : This uses writing to flash using registers.
