### ISSUE TITLE
PlatformIO IDE support

### ISSUE THREAD

**Issue by unCleanCode** [sandeepmistry/arduino-nRF5#218]
It is a real pain to use Arduino IDE for file editing, especially when you have a project with a lot of files, custom libraries, own libraries, etc.
I see that a lot of develpers switched to PlatformIO IDE (so am I), so could you please port your library to this IDE? I tried to make it work with it but didn't succeed (maybe you know how to make it work?)

I'd really be glad usgin your library for nRF52 development, but Arduino IDE limits me

**Comment by dlabun** [comment]
To be honest I know nothing about Platform IO, but somehow they are saying they already support the Nordic nRF family and link directly to this repository... I would recommend checking with them on how they support this repository.
