### ISSUE TITLE
millis() does not work as it should it overflows after ~8 minutes (overflows never gets incremented)

### ISSUE THREAD

**Issue by TraxXavier** [sandeepmistry/arduino-nRF5#220]
Hello,

I have a problem with the millis() function, it always overflows after roughly 8 minutes of operation, also the overflow handler for the RTC1 (RTC1_IRQHandler) is never invoked hence the overflows variable never incremented.

Also as far as I see the delay() function can fail if an overflow of millis offurs.

**Comment by TraxXavier** [comment]
the fix:
delay.c

uint32_t millis( void )
{
  uint64_t ticks = (uint64_t)((uint64_t)overflows << (uint64_t)24) | (uint64_t)(NRF_RTC1->COUNTER); // Trax Fix: 24 bit counter not 32

  return (ticks * 1000) / 32768;
}

uint32_t micros( void )
{
  uint64_t ticks = (uint64_t)((uint64_t)overflows << (uint64_t)24) | (uint64_t)(NRF_RTC1->COUNTER); // Trax Fix: 24 bit counter not 32

  return (ticks * 1000000) / 32768;
}

wiring.c

void init( void )
{
  NVIC_SetPriority(RTC1_IRQn, 15);
  NVIC_ClearPendingIRQ(RTC1_IRQn);
  NVIC_EnableIRQ(RTC1_IRQn);

  NRF_CLOCK->LFCLKSRC = (uint32_t)((CLOCK_LFCLKSRC_SRC_RC << CLOCK_LFCLKSRC_SRC_Pos) & CLOCK_LFCLKSRC_SRC_Msk);
  NRF_CLOCK->TASKS_LFCLKSTART = 1UL;

  NRF_RTC1->PRESCALER = 0;
  NRF_RTC1->INTENSET = RTC_INTENSET_OVRFLW_Msk; // Set the overflow interrupt properly
  NRF_RTC1->TASKS_START = 1;
}

**Comment by sandeepmistry** [comment]
@TraxXavier could you please open a pull request for this suggestion.

**Comment by TraxXavier** [comment]
will have to look into how to do that :D

**Comment by sandeepmistry** [comment]
@TraxXavier any progress on this?

**Comment by jeremypoulter** [comment]
I think this has already been fixed in #87

**Comment by sandeepmistry** [comment]
@jeremypoulter thanks, let's close for now then.
