### ISSUE TITLE
Serial communication only works with softdevice "none" on PCA1000X boards that require hardware flow control

### ISSUE THREAD

**Issue by oyooyo** [sandeepmistry/arduino-nRF5#225]
Some PCA1000X boards require hardware flow control for Serial port communication. On such boards, serial port communication currently only works when selecting softdevice "none".
This appears to be due to the compiler flag `-D{board.variant}` missing in the _build.extra_flags_ of the PCA1000X softdevices S110 and S130, which somehow leads to `PIN_SERIAL_RTS` and `PIN_SERIAL_CTS` being undefined, and thus the Serial port not being correctly initialized:
```
#if defined(PIN_SERIAL_CTS) && defined(PIN_SERIAL_RTS)
  Uart Serial( NRF_UART0, NRF_UART0_IRQn, PIN_SERIAL_RX, PIN_SERIAL_TX, PIN_SERIAL_CTS, PIN_SERIAL_RTS );
#else
  Uart Serial( NRF_UART0, NRF_UART0_IRQn, PIN_SERIAL_RX, PIN_SERIAL_TX );
#endif
```
PR #224 intends to fix this problem.

**Comment by sandeepmistry** [comment]
Fixed via PR #224.
