### ISSUE TITLE
Travis running IDE 1.8.1

### ISSUE THREAD

**Issue by dlabun** [sandeepmistry/arduino-nRF5#230]
Currently when Travis does a build it's using Arduino IDE 1.8.1... Any particular reason we're still on 1.8.1 or should we move up to 1.8.5?

**Comment by sandeepmistry** [comment]
@dlabun good observation, I think we can update to 1.8.5, I just forgot to update that's why it's an old version.

Would you like to submit a PR to get this done? If Travis CI passes we can merge the PR.

**Comment by sandeepmistry** [comment]
Closed via https://github.com/sandeepmistry/arduino-nRF5/commit/7df754344d4eddeb2871b3b1f1ff93051d0302e0.
