### ISSUE TITLE
BLE example?

### ISSUE THREAD

**Issue by laterps** [sandeepmistry/arduino-nRF5#232]
Hi is there any BLE example from this library? What i meant is that i can work correctly with this library but not with redbear lab library.I dont know the reason why when i use your library i can flash the nrf52832 custom board (i made it) but when I use the red bear lab I can not flash de nrf52832 but i can flash the nrf52832 sparkfun board and i am fllashing it with swd protocol
Can any one help me?

**Comment by sandeepmistry** [comment]
Please see https://github.com/sandeepmistry/arduino-nRF5#recommend-ble-libraries
