### ISSUE TITLE
Is the WT51822-S4AT board supported?

### ISSUE THREAD

**Issue by probonopd** [sandeepmistry/arduino-nRF5#239]
Is the Wireless-Tag Technology WT51822-S4AT supported?

It currently shows up as the [cheapest nRF5 module on eBay](https://www.ebay.com/sch/i.html?_from=R40&_sacat=0&_nkw=NRF51822&_sop=15) under the name "NRF51822-04".

http://www.wireless-tag.com/wireless_module/BLE/WT51822-S4AT.html

It seems like P0.03, P0.04, P0.09, P0.10, P0.13 are available. With these, is it possible to use
* i2c
* SPI

devices from within the Arduino environment on this board?

http://www.nordicsemi.com/node_206/node_305/Product-Related-News/Nordic-powered-Bluetooth-Smart-module-simplifies-development-of-wireless-wearables-toys-and-smart-home-solutions

**Comment by dlabun** [comment]
Currently it's not supported but you can use the generic nRF51 device and modify it to work with that board.

**Comment by probonopd** [comment]
So you think hardware-wise there are no issues?

**Comment by dlabun** [comment]
Hard to tell since it's pre-programmed to act as a UART to Bluetooth bridge. I would check with the manufacturer first to see if the board is designed to be reprogrammed.

**Comment by probonopd** [comment]
According to the data sheet, it has pins for

|   Pin	|  Signal 	|   Comment	|   
|---	|---	|---	|
|pin10 | SWDIO  | Debug data input|
|pin11 | SWDCLK  | Debug clock signal input|

Is there anything else that needs to be in the spec in order for it to be programmable with this core?

**Comment by sandeepmistry** [comment]
That should be it and an external programmer that supports programming via SWDIO/SWCLK.

**Comment by tamasharasztosi** [comment]
Hello! 

Did you managed to make it work? 
Could you please guide me, I would like to do the same thing with that module, I will hook it up with an ST-Link V2, is it going to work?

Thank you!
