### ISSUE TITLE
Please enable the Wiki

### ISSUE THREAD

**Issue by probonopd** [sandeepmistry/arduino-nRF5#253]
Please enable https://github.com/sandeepmistry/arduino-nRF5/wiki and let users edit, so that we can collect documentation (e.g., about boards and pinouts) there. Thanks.

**Comment by sandeepmistry** [comment]
@dlabun any thoughts on this?

The wiki is already enabled from what I see.

**Comment by dlabun** [comment]
Having a wiki isn't a bad idea, I am just concerned about having to police it for vandalism. Can it be modified through the PR process?

**Comment by probonopd** [comment]
I don't think so but from my experience people on GitHub are generally civilized. In case it turns out this isn't the case, you can limit edit rights to collaborators; but I think this would take away from the power of a wiki.

**Comment by sandeepmistry** [comment]
I'm up for trying the wiki. We can always disable it if things don't work out.

I've started a welcome page: https://github.com/sandeepmistry/arduino-nRF5/wiki
