### ISSUE TITLE
nrf51822 cant pair with android through bluetooth setting menu.

### ISSUE THREAD

**Issue by sashisekhar** [sandeepmistry/arduino-nRF5#266]
hello,
i am a newbie in nrf & i tried some example code with bleperipheral library & its working fine. i m using nrf tool kit to connect my phone to my device. but when i try to connect with the device through android's bluettoth setting menu then a message pops up saying "pairing is rejected by the device". how may i pair it with the device. i hv digged into the matter & found out that when a pairing request is sent from the mobile then bleEvt->evt.gap_evt.params.auth_status.auth_status=133(0x85). so 0x85 means  BLE_GAP_SEC_STATUS_PAIRING_NOT_SUPP. but how can i manage to allow the pairing. may be m getting anything wrong & clueless what to do next. please help.
thanks in advance

**Comment by dlabun** [comment]
The nRF tool kit is only designed for Nordic's example applications, it will most likely not pair with non-Nordic applications. I recommend you either post your question under the BLEperipheral library issue ticket or try reaching out to the Nordic forums to see if there's a solution.
