### ISSUE TITLE
nRF51 Generic Code Upload/Build Problem

### ISSUE THREAD

**Issue by eren23** [sandeepmistry/arduino-nRF5#268]
Hi,
I've tried to upload code to my generic nRF51 board, but after hex upload finishes i can't see any softdevice or application file on nRFgo Studio. I'm choosing the board, softdevice, and taking output as hex file after that i'm uploading code via nRFGo Stuido but as i mentioned above i can't see any files up here.

**Comment by eren23** [comment]
Thank you for your reply, so can i upload my code with JLink just on Arduino IDE like in nRFgo Studio?

**Comment by eren23** [comment]
After i upload my code with the instructions 
![07a81b70d4552bbc7069bb2e5087fdf3fc907a778ccbb69e32 pimgpsh_fullsize_distr](https://user-images.githubusercontent.com/20106221/38917845-98f8e468-42f4-11e8-9797-0a69e6a5e1fa.jpg)

**Comment by dlabun** [comment]
Did you follow the directions in the readme file to install the JLink driver?

**Comment by eren23** [comment]
Yes i've followed it, i can start it over if you don't have any other suggestions for now.

**Comment by dlabun** [comment]
From the screen shot it's indicating that the LIBUSB driver is not installed. The only recommendation I have left is to remove anything JLink related and follow the install instructions on this repository... Don't install the Segger drivers or nRF Studio.

**Comment by eren23** [comment]
Okay ty i will try your suggestions, i will write back here as soon as i try them.

**Comment by eren23** [comment]
![a4d048b6a19f767125f48430ba8290d9becd1cfc8f9753973d pimgpsh_thumbnail_win_distr](https://user-images.githubusercontent.com/20106221/38977244-77dcbaa2-43bc-11e8-8d86-9c35349dadeb.jpg)
After i upload my code this is the output now, is this seem fine?

**Comment by eren23** [comment]
Now i'm trying a basic code to my nRF51 DK to check my PCB is ok but i couldn't get any solutions either. Here is the picture:
![07d89df7497613ffe12c386fa7afa9c8fabf033b615b73cd06 pimgpsh_fullsize_distr](https://user-images.githubusercontent.com/20106221/38987998-5f52a816-43da-11e8-9209-922455d0157e.jpg)
I think i'm failing about the very basics but i can't get it what are those fails, do you have any other ideas about that matter?

**Comment by dlabun** [comment]
Did you have the Arduino IDE open while uninstalling / install the LIBUSB driver?

**Comment by eren23** [comment]
I can't say anything for sure but i'll make sure it closed and try it again.

**Comment by eren23** [comment]
I've tried it all but the result is still the same, if you don't mind can you explain what should we do exatcly with zadig?

**Comment by dlabun** [comment]
I'm not sure what you are asking. I think at this point you simply have a bunch of programs and drivers conflicting with each other... How you fix this problem I do not know.

**Comment by sandeepmistry** [comment]
Closing for now due to lack of activity.
