### ISSUE TITLE
Support for ble mesh using nrf52 

### ISSUE THREAD

**Issue by Nakul93** [sandeepmistry/arduino-nRF5#275]
Is there mesh examples for nrf52 in arduino...if not then when will it be available?

**Comment by probonopd** [comment]
Duplicate of https://github.com/sandeepmistry/arduino-nRF5/issues/62

**Comment by dlabun** [comment]
As listed in the readme: This Arduino Core does not contain any Arduino style API's for BLE functionality

**Comment by probonopd** [comment]
...but its sister project, https://github.com/sandeepmistry/arduino-BLEPeripheral does :-) maybe ask there.
