### ISSUE TITLE
Analogue outputs on BBC Micro Bit

### ISSUE THREAD

**Issue by technoblogy** [sandeepmistry/arduino-nRF5#276]
In the variant.h file for the BBC Micro Bit shouldn't the line:

    #define NUM_ANALOG_OUTPUTS  (0u)

be:

    #define NUM_ANALOG_OUTPUTS  (20u)

because any digital pin can be used as an analogue output?

**Comment by carlosperate** [comment]
Looks like that macro is meant to identify DACs in the microcontroller (https://github.com/sandeepmistry/arduino-nRF5/issues/130), so since the analog out is a software PWM, the macro in this case is correctly set to `0`.

**Comment by technoblogy** [comment]
OK, understood. Thanks.
