### ISSUE TITLE
Arduino BLE example (advertising without connection)

### ISSUE THREAD

**Issue by tcpipchip** [sandeepmistry/arduino-nRF5#281]
Sir, 
Is there some example that make advertising to all without make connection ?
For example, all scannes can see the state of BUTTON,
I found one in mbed, the BLE_GAPButton example. Have you similar example to ARDUINO ?

**Comment by dlabun** [comment]
As stated in the readme, this project does not include Bluetooth support. You can try looking here:
https://github.com/sandeepmistry/arduino-BLEPeripheral
