### ISSUE TITLE
Use P0.00 as ADC Pin

### ISSUE THREAD

**Issue by francesco98** [sandeepmistry/arduino-nRF5#284]
Hi,

I'm reading http://infocenter.nordicsemi.com/pdf/nRF51822_PS_v3.3.pdf and in section 2.2 it seems possibile to use P0.00 as Analog Input. Is it possibile? Which is its name in code?

Thanks

**Comment by francesco98** [comment]
Thanks for your answer.
I'm using CJMCU-8223 that is a board with nRF51822 and LIS3DH (accelerometer). Unfortunally, on this board the only ADC pin is P0.00 on which I want connect the Pulse Sensor ([https://pulsesensor.com/](https://pulsesensor.com/)). Can you help me to use this pin?

Thank you

**Comment by yogeshwaran774** [comment]
Hi, i am using cj-mcu 8223 and i have the nrfsdk but i don't have datasheet of cjmcu. i googled it but still can't find any resources. i uploaded some example codes by compiling in keil u5 but no results after uploading. so can anyone provide me a link of cjmcu data sheet and sample codes.

**Comment by sinaban** [comment]
this is a terrible board. there is no data and even no reset pin, reset pin for nrf52811 is p0.21, unfortunately, we have not pinout for it in PCB,
