### ISSUE TITLE
Is it possible to use this with arbitrary consumer devices (wristband)?

### ISSUE THREAD

**Issue by diimdeep** [sandeepmistry/arduino-nRF5#285]
Hello, I have Bong wristband with nRF52832
Is it possible to use this to flash it with something?

**Comment by diimdeep** [comment]
![2017-02-20 23-31-50](https://user-images.githubusercontent.com/485713/41064991-dd63ac2e-69e5-11e8-9d6d-bb55188da086.jpg)
![2017-02-20 23-48-53](https://user-images.githubusercontent.com/485713/41065005-eea4f060-69e5-11e8-9c05-b3529b6c9088.JPG)
![2017-02-20 23-30-34](https://user-images.githubusercontent.com/485713/41065037-06c127f4-69e6-11e8-8ba3-633ee60601c3.JPG)

**Comment by dlabun** [comment]
If you knew the pin out and completely wiped out the existing programming, then possibly yes you could.
