### ISSUE TITLE
ANT protocol

### ISSUE THREAD

**Issue by 204maker** [sandeepmistry/arduino-nRF5#286]
Does this core support ANT+ protocol for transmit/receive data?
Such in the case of receiving data from an ANT sensor and re-transmitting the same data to a BLE device.

**Comment by dlabun** [comment]
No it does not... The ANT soft device requires an NDA from Garmin and the ANT+ protocol requires even more paperwork and testing on top of the NDA.

**Comment by dlabun** [comment]
Closing as resolved
