### ISSUE TITLE
How is hardware to be connected when flashing a SoftDevice?

### ISSUE THREAD

**Issue by nhnifong** [sandeepmistry/arduino-nRF5#292]
1. Should I connect the BT module to the arduino, and the arduino to the PC?
2. If the name of the bluetooth module is selected in the tools > board menu, where would it be specified which kind of arduino board the BTLE module is connected to?
3. Where would I specify which of the arduino's hardware serial ports the BTLE module is connected to?

**Comment by nhnifong** [comment]
Is this an acceptable ST-link programmer?
https://www.amazon.com/gp/product/B00RYVLN4U/ref=oh_aui_detailpage_o01_s00?ie=UTF8&psc=1

**Comment by dlabun** [comment]
It's not a genuine ST-Link programmer so it's totally use at your own risk, I won't tell you it's okay to use.
