### ISSUE TITLE
nRF52 variant.cpp missing pin 10?

### ISSUE THREAD

**Issue by VinceGa** [sandeepmistry/arduino-nRF5#293]
Isn't pin 10 supposed to be included in g_ADigitalPinMap[] in variant.cpp?
I see in variant.h , we have:
static const uint8_t SS   = 10 ;

Correct me if I am wrong.

**Comment by dlabun** [comment]
It all depends on which variant you’re using... It’s possible the particular board you are using does need / use it.

**Comment by VinceGa** [comment]
If we have
 static const uint8_t SS   = 10 ; //SPI SS is using Pin 10
in variant.h
but Pin 10 is not in the g_ADigitalPinMap[] in variant.h,
Will that be a problem?
Thanks.

**Comment by dlabun** [comment]
Probably not, but again I don't know which variant you're looking at.

**Comment by dlabun** [comment]
Close due to lack of response from OP
