### ISSUE TITLE
Error while flashing SoftDevice to nRF52DK

### ISSUE THREAD

**Issue by austinfennacy** [sandeepmistry/arduino-nRF5#299]
hey, I'm using the nRF52DK and have successfully uploaded code to the board by choosing `Tools -> Softdevice: "None"`. Now I'm interested in using the board's Bluetooth functionality, but am encountering an error while flashing SoftDevice.

In the README: Flashing a SoftDevice, I got to step "8. Select Tools -> nRF5 Flash SoftDevice" before anything seemed off. After selecting `Tools` -> `nRF5 Flash Soft Device`, I did not see a licence agreement as indicated by step 9, though Windows Firewall did ask me to allow Arduino to download files. After allowing, I saw this message:
```
Downloading 'http://www.nordicsemi.com/eng/content/download/95151/1606944/file/s132_nrf52_2.0.0.zip' ...
.done
Open On-Chip Debugger 0.10.0-dev-00254-g696fc0a (2016-04-10-10:13)
Licensed under GNU GPL v2
For bug reports, read
	http://openocd.org/doc/doxygen/bugs.html
debug_level: 0
0
adapter speed: 10000 kHz
cortex_m reset_config sysresetreq
nrf52.cpu: target state: halted
target halted due to debug-request, current mode: Thread 
xPSR: 0x01000000 pc: 0xfffffffe msp: 0xfffffffc
** Programming Started **
auto erase enabled
Error: couldn't open C:\Users\austinfennacy\AppData\Local\Arduino15\packages\sandeepmistry\hardware\nRF5\0.5.1/cores/nRF5/SDK/components/softdevice/s132/hex/s132_nrf52_2.0.1_softdevice.hex
embedded:startup.tcl:454: Error: ** Programming Failed **
in procedure 'program' 
in procedure 'program_error' called at file "embedded:startup.tcl", line 510
at file "embedded:startup.tcl", line 454
Error while flashing SoftDevice.
```
Things seem to go wrong at the line with `Error: couldn't open C:\Users\austinfennacy\AppData\Local\Arduino15\packages\sandeepmistry\hardware\nRF5\0.5.1/cores/nRF5/SDK/components/softdevice/s132/hex/s132_nrf52_2.0.1_softdevice.hex`, I checked the `hex` folder and didn't see `s132_nrf52_2.0.1_softdevice.hex`, just a `.gitkeep` file.

I checked previous issues in this repo, not sure if this comment applies but found that this core needs to be programmed by SWD (#241), perhaps I'll try flashing via SWD next instead of using USB -> J-Link-OB -> nRF52832?

Any thoughts on how to get `s132_nrf52_2.0.1_softdevice.hex` to download / appear in that folder?

**Comment by dlabun** [comment]
I'm not sure why the download failed, but you can manual download and extract the SD from this link:

http://www.nordicsemi.com/eng/content/download/95151/1606944/file/s132_nrf52_2.0.0.zip

**Comment by austinfennacy** [comment]
Awesome, I placed `s132_nrf52_2.0.1_softdevice.hex` from the download into the folder I mentioned and the SoftDevice flashed successfully. Building with `Tools -> Softdevice: "S132"` also successfully compiles and uploads. Thanks!

**Comment by deibid** [comment]
Brilliant solution!
Sadly, the URL is no longer valid but I was able to find it.
Follow the these steps to get it.

* Open this URL https://www.nordicsemi.com/Software-and-Tools/Software/S132/Download#infotabs
* Under downloads, find SoftDevice S132
* Select version 2.0.1
* Download the zip file and extract it
* Look for the "s132_nrf52_2.0.1_softdevice.hex" file and copy it to the directory highlighted in your error message.

Hope this helps

**Comment by tpitman** [comment]
Does the soft device have to be version 2.0.1? It looks like you have hard coded the version in the name. Is there a way to change that to a later soft device? Is your SDK tied to that specific version of thee soft device? Can that be changed or made more generic?

**Comment by aguileraGit** [comment]
I never get a directory to copy the file to. Error message:
```
Arduino: 1.8.9 (Mac OS X), Board: "Generic nRF51, 16 kB RAM, 256 kB flash (xxaa), S110, RC Oscillator"

Downloading 'http://www.nordicsemi.com/eng/content/download/80234/1351257/file/s110_nrf51_8.0.0.zip' ...
Error while flashing SoftDevice.
java.io.FileNotFoundException: http://www.nordicsemi.com/eng/content/download/80234/1351257/file/s110_nrf51_8.0.0.zip

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

```

Verbose checked.

**Comment by Carbon18** [comment]
I just updated the SoftDevice S130 with this link:

https://www.nordicsemi.com/-/media/Software-and-other-downloads/SoftDevices/S130/s130nrf51201.zip

It's downloaded now, but I don't understand where I need to change the hardcoded version name from 2.0.0 to 2.0.1 ? @tpitman or anyone?

**Comment by tpitman** [comment]
It has been so long I can't remember. I am sorry.

**Comment by Carbon18** [comment]
I can't remember what I had for breakfast so I understand... :D

**Comment by Carbon18** [comment]
found it:  s13x_nrf5x migration document.pdf
