### ISSUE TITLE
nRF5FlashSoftDevice support BusPirate?

### ISSUE THREAD

**Issue by sabas1080** [sandeepmistry/arduino-nRF5#30]
Hi

I have a Bus Pirate, could you use it to flash?

Thanks

**Comment by sabas1080** [comment]
I have compile a version of OpenOCD for Linux 64 with support for Buspirate but i have the next error

`Error: Can't change session's transport after the initial selection was made
Error while flashing SoftDevice.`

My cfg for Buspirate is

`interface buspirate

#source [find interface/buspirate.cfg]

# you need to specify port on which BP lives
buspirate_port /dev/ttyUSB0


# increase working area to 16KB
set WORKAREASIZE 0x4000

reset_config none separate

transport select swd`

**Comment by sandeepmistry** [comment]
@sabas1080 what if you supply the configuration to openocd on the command line?

```
openocd -f interface/buspirate.cfg -c "buspirate_port /dev/ttyUSB0; set WORKAREASIZE 0x4000; reset_config none separate; transport select swd"
```

Once you get this working, we can try to incorporate into `programmers.txt` and `platform.txt`

**Comment by sabas1080** [comment]
@sandeepmistry from terminal:
![openocd](https://cloud.githubusercontent.com/assets/2874292/17651921/51663970-6236-11e6-8d44-537f30728079.png)

**Comment by sabas1080** [comment]
Here program nRF51 with Ruby and Bus Pirate 

http://floe.butterbrot.org/matrix/hacking/nrf/

**Comment by sabas1080** [comment]
I 'm uploading firmware compiled in Arduino IDE and Bus Pirate with [programmer](https://github.com/floe/programmer) and softdevice130

`ruby -I. flash.rb --adapter=buspirate,dev=/dev/ttyUSB0 s130_nrf51_2.0.1.bin 0x00000000
`

I 'm trying to blink

`ruby -I. flash.rb --adapter=buspirate,dev=/dev/ttyUSB0 Blink.ino.hex 0x0001C000
`

but I can not get the blink

**Comment by sandeepmistry** [comment]
@sabas1080 cool!

Since the Bus Pirate will require Ruby, not sure if this repo will include support for it out of the box. If you're looking for an inexpensive programmer ST-Link clones work well (https://www.adafruit.com/products/2548) also available on eBay, etc.

 Can you try with the S110 soft device? I think your problem might be related to #22. Could you please try adjust the RAM config and continue the discussion there?

**Comment by sabas1080** [comment]
Thanks @sandeepmistry 

Working test of the Library [nRFPeripehtal](https://github.com/sandeepmistry/arduino-BLEPeripheral) with S110 Soft

The Instructions are as follows:

Convert .hex to .bin
`arm-none-eabi-objcopy -I ihex -O binary s110_nrf51_8.0.0_softdevice.hex s110_nrf51_8.0.bin`

flash with next command

`ruby -I. flash.rb --adapter=buspirate,dev=/dev/cu.usbserial-xxxxxxxx s110_nrf51_8.0.bin 0x00000000`

Next convert scketch of .hex to .bin
`arm-none-eabi-objcopy -I ihex -O binary test.ino.Waveshare_BLE400.hex test.bin
`
and flash with next command
`
ruby -I. flash.rb --adapter=buspirate,dev=/dev/cu.usbserial-xxxxxxxx Blink.bin 0x00018000`

I am going to buy an STM32 board for try with Black Magic Probe if repo will not support for it out the box
