### ISSUE TITLE
ID107HR device stops working after a while

### ISSUE THREAD

**Issue by scientistnobee** [sandeepmistry/arduino-nRF5#304]
Hi, I have a strange problem. My code on the ID107HR (nRF51822) is running for a while (a few hours) then it stops working. What I mean is that it stops communicating on the serial port and stops refreshing the values on the OLED screen. But still the LEDs of HR sensor are switched on for at least 2-3 hours until the battery is completely discharged. Then if I charge the device again, it works for a while and again same problem repeats. 

So far, I have tried the following

1) I have tried to delete the Bleserial lines and see if the FITNESS tracker is working fine without BleSerial. the result is that, it worked perfectly.

2) I removed all the lines corresponds to Serial Print, to see if there are any conflicts. It didn't change the behaviour. My device still stops working after a while.

3)  I removed all delay functions and replaced them with millis. Although it didn't help much, at least the last updated values are shown on the OLED screen and they are staying there forever. Before that OLED screen used to go black without showing any values.

4) When I connect the device back to BMP, the device starts working again, although BMP is not connected to any USB port. I think the device is getting reset as soon as it is connected to the BMP.

Please let me know if there is any way to troubleshoot this problem.

My code is here
https://github.com/scientistnobee/Robot_learn/blob/master/Tubidity_no_serial_port2.ino

**Comment by dlabun** [comment]
Close as a duplicate issue on the BLE peripheral issue tracker .
