### ISSUE TITLE
Can all this be used for programming the nRF52840?

### ISSUE THREAD

**Issue by rabbithat** [sandeepmistry/arduino-nRF5#310]
About a year ago I used it to program the nRF52832, and that worked fine.  Do I need to do anything different to compile and upload to the nRF52840 from within the Arduino IDE?

**Comment by dlabun** [comment]
Based on the Nordic documentation I am going to say that it won't work with this project as it's too new for the SDK version we're using. That doesn't mean you could try, maybe it will work with code built for the nRF52832.

**Comment by michapr** [comment]
Somebody have tried it? It's interesting for me too to use the nRF52840 :)

Thanks!

**Comment by Erickrk** [comment]
Hey guys, I just went through the same question, nobody tried?
