### ISSUE TITLE
can't install softdevice

### ISSUE THREAD

**Issue by kriswiner** [sandeepmistry/arduino-nRF5#312]
I (stupidly) upgraded to the latest 0.6.0 core and now I cannot load the softdevice and i am getting this error:

** Programming Started **
auto erase enabled
Error: couldn't open C:\Users\kris\AppData\Local\Arduino15\packages\sandeepmistry\hardware\nRF5\0.6.0/cores/nRF5/SDK/components/softdevice/s132/hex/s132_nrf52_2.0.1_softdevice.hex
embedded:startup.tcl:454: Error: ** Programming Failed **
in procedure 'program' 
in procedure 'program_error' called at file "embedded:startup.tcl", line 510
at file "embedded:startup.tcl", line 454
Error while flashing SoftDevice.

It seems the softdevice can;t be loaded from the git repository. I am sure I followed all of the directions but I must missing something... Can someone please help me fix this?

**Edited for length**

**Comment by dlabun** [comment]
@kriswiner You can manually download and unzip the Soft Device from http://www.nordicsemi.com/eng/content/download/95151/1606944/file/s132_nrf52_2.0.1.zip

@sandeepmistry I think the softdevices.txt file needs to be updated to change the file name from 2.0.0 to 2.0.1.zip.

**Comment by kriswiner** [comment]
Just copied it into the appropriate directory by hand and it works now.

**Comment by kriswiner** [comment]
Interesting that I2C also works with the nRF52 with 0.5.1, so something has been fixed.

**Comment by dlabun** [comment]
A patch was merged 10 months ago fixing I2C on the nRF52.

**Comment by kriswiner** [comment]
Thanks, glad it now works out of the box. When is the soft-device support
going to be upgraded to the latest soft device?

**Comment by dlabun** [comment]
**Workaround: Manually download and extract the soft device**
For the S132 SD please use this link:
http://www.nordicsemi.com/eng/content/download/95151/1606944/file/s132_nrf52_2.0.1.zip

For the S130 SD please use this link:
http://www.nordicsemi.com/eng/content/download/95150/1606929/file/s130_nrf51_2.0.1.zip

**Comment by kriswiner** [comment]
Yes, I did this and now it works fine.

I hope we can muster enough support to upgrade the Arduino core to use the
latest SDK and softdevice; this will help general (and commercial) use of
the core going forward.

**Comment by dlabun** [comment]
Sorry Kris, that wasn't directed at you... I'm using this as a general tracker as this is a global issue.

**Comment by dwilday** [comment]
Could someone elaborate on which directory this needs to be unzipped into?

**Comment by kriswiner** [comment]
From the repo front page instructions:
<SKETCHBOOK>/tools/nRF5FlashSoftDevice/tool/

**Comment by dwilday** [comment]
Thanks!  Though storing the hex file, zip file, unzipped directory or it's entire contents in that folder doesn't seem to work.

**Comment by kriswiner** [comment]
Yeah, the .jar file goes there, the 132 softdevice hex file goes here:

C:\Users\kris\AppData\Local\Arduino15\packages\sandeepmistry\hardware\nRF5\0.6.0\cores\nRF5\SDK\components\softdevice\s132\hex

or equivalent...

**Comment by dwilday** [comment]
Kris,
That's what I'm trying to find out.  The Mac equivalent of that path.  I feel I've looked in all the usual places (Arduino.app/Contents, Application Support, etc) with no luck.

**Comment by kriswiner** [comment]
Look in preferences in the"file" Arduino IDE tab at the bottom is a link
you can click on, this should allow you to get to the right directory
starting with packages, etc....

I think this needs to be spelled out a little better in the Arduino core
instructions; I liked it better when this was all done automagically!

**Comment by dwilday** [comment]
Thank you, Kris!

**Comment by choich** [comment]
I have same problem with nrf52 DK.

** Programming Started **
auto erase enabled
Error: couldn't open /Users/choichanhwan/Library/Arduino15/packages/sandeepmistry/hardware/nRF5/0.5.1/cores/nRF5/SDK/components/softdevice/s132/hex/s132_nrf52_2.0.1_softdevice.hex
embedded:startup.tcl:454: Error: ** Programming Failed **
in procedure 'program' 
in procedure 'program_error' called at file "embedded:startup.tcl", line 510
at file "embedded:startup.tcl", line 454
Error while flashing SoftDevice.

http://www.nordicsemi.com/eng/content/download/95151/1606944/file/s132_nrf52_2.0.1.zip
I downloaded and unZip it to <SKETCHBOOK>/tools/nRF5FlashSoftDevice/tool/
but when I click nRF5 Flash SoftDevice button, the same error occurs.

When I unzip and move the file and try to upload the example without nRF5 Flash SoftDevice

~/Library/Arduino15/packages/sandeepmistry/tools/gcc-arm-none-eabi/5_2-2015q4/bin/arm-none-eabi-g++: no such file or directory

I get this error.

What can I do? Anyone help me...

**Comment by sandeepmistry** [comment]
@kriswiner have you followed: https://github.com/sandeepmistry/arduino-nRF5#flashing-a-softdevice

@choich please open a new issue, it seems like your install is not correct.

**Comment by dlabun** [comment]
@Sandeeepmistry there’s was a typo were we had the IDE looking for 2.0.0 but Nordic is serving up 2.0.1. I’ve updated the SD file to request the proper file from Nordic, next release will fix everything.

**Comment by floe** [comment]
Seems like this is still an issue, the links in https://github.com/sandeepmistry/arduino-nRF5/issues/312#issuecomment-422204930 all return 404 errors.

**Comment by dlabun** [comment]
@sandeepmistry Nordic just completely changed their website and you can no longer link to Soft Device files.... How do you want to hand this?

**Comment by kriswiner** [comment]
And I will ask again, can't we get an upgrade of the softdevice to the
latest? Lot's of bug fixes and new features are unavailable now while stuck
with the very old version required currently.

**Comment by dlabun** [comment]
@kriswiner Simple Answer: No

Full Answer: Updating to the new soft devices requires updating all of the SDK files in this project. At a certain point as you update SDK versions Nordic discontinued support for the nRF51 family. We would need to figure out how to support two different SDK versions within this project OR we'd need to split the project into a nFR51 version and a nRF52 version. So far there have been no community attempts at updating to a new SD or SDK nor is it something I am working on.

**Comment by sandeepmistry** [comment]
> Nordic just completely changed their website and you can no longer link to Soft Device files.... How do you want to hand this?

@dlabun Can we just update the URL in `softdevices.txt`?

Unless they updated the license of the files, I don't think we can host/distribute in another URL. Did you have something else in mind?

**Comment by dlabun** [comment]
@sandeepmistry They updated the website in such a way that you have to specify which soft devices you want and then the website gives you an on-demand compiled ZIP file with all of the SDs you selected. I could not find an easy way around it, Only solution I have is a note in the ReadMe saying to go download everything manual from Nordic

**Comment by sandeepmistry** [comment]
We could change the downloader to do a HTTP POST instead of GET?

The following curl commands seems to work for me:
```
curl -vvvv  -X POST https://www.nordicsemi.com/api/sitecore/Products/MedialibraryZipDownload2 -d ids=DBBEB2467E4A4EBCB791C2E7BE3FC7A8
```

**Comment by dlabun** [comment]
Unfortunately that's outside of my league of programming... But I can certainly test a patch on my end to make sure it'll work

**Comment by floe** [comment]
StackOverflow to the rescue! (yeah, I know, lazy me): if POST is needed, then instead of [`URL(url).openStream()`](https://github.com/sandeepmistry/arduino-nRF5/blob/master/extras/ide-tools/nRF5FlashSoftDevice.java#L106), we would just need to use the code snippet from here: https://stackoverflow.com/questions/2793150/how-to-use-java-net-urlconnection-to-fire-and-handle-http-requests

```
URLConnection connection = new URL(url).openConnection();
connection.setDoOutput(true); // Triggers POST.
connection.setRequestProperty("Content-Type", "application/x-www-form-urlencoded");

try (OutputStream output = connection.getOutputStream()) {
    output.write(new String("ids=DBBEB2467E4A4EBCB791C2E7BE3FC7A8").getBytes());
}

InputStream is = connection.getInputStream();
```

IMHO this should do the trick, although it's completely untested. No more time ATM, sorry.

**Comment by enauman** [comment]
@choich did you have success? I am having the same issue with flashing a softdevice S110, "~/Library/Arduino15/packages/sandeepmistry/tools/gcc-arm-none-eabi/5_2-2015q4/bin/arm-none-eabi-g++: no such file or directory" and I see in that directry that file is missing. I have manually downloaded the nordicsemi hex file for S110 to the correct location.

**Comment by enauman** [comment]
I uninstalled and reinstalled the nRF5 package and it's working now...

**Comment by embedream** [comment]
download form: https://www.nordicsemi.com/Software-and-Tools/Software/S132/Download#infotabs
select ver 2.0.1.
exact , copy : s132_nrf52_2.0.1_softdevice.hex 
to:  C:\Users\<username>\AppData\Local\Arduino15\packages\sandeepmistry\hardware\nRF5\0.6.0\cores\nRF5\SDK\components\softdevice\s132\hex

**Comment by SL06** [comment]
On the mac, the path is:
 ▸ ⁨Users ▸ <username>▸ ⁨Library ▸ ⁨Arduino15⁩ ▸ ⁨packages⁩ ▸ ⁨sandeepmistry⁩ ▸ ⁨hardware⁩ ▸ ⁨nRF5⁩ ▸ ⁨0.6.0⁩ ▸ ⁨cores⁩ ▸ ⁨nRF5⁩ ▸ ⁨SDK⁩ ▸ ⁨components⁩ ▸ ⁨softdevice⁩ ▸ ⁨s132⁩ ▸ ⁨hex⁩

**Comment by SL06** [comment]
I am struggling with the BLE_serial exemple.  No problem compiling but it advertised "Arduino" instead of "UART" like in the script and communication don't work.  My iPad the nrf52 Toolbox UART log says :  Error, writing is not permitted.  The BLE_app_UART exemple from the nrf52 SDK work just fine with Segger.

**Comment by dlabun** [comment]
I've locked this issue due to the number of unrelated comments creeping in
