### ISSUE TITLE
Flash Soft Device Error

### ISSUE THREAD

**Issue by dwilday** [sandeepmistry/arduino-nRF5#313]
When attempting to flash the softdevice 130 to an nRF51 Dev Kit I received the following error:

> Error while flashing SoftDevice.
> java.io.IOException: Server returned HTTP response code: 403 for URL: http://www.nordicsemi.com/eng/content/download/95150/1606929/file/s130_nrf51_2.0.0.zip

**Comment by dlabun** [comment]
This is a known issue, please see issue #312 for the work around
