### ISSUE TITLE
Pin Mapping of Generic NRF51

### ISSUE THREAD

**Issue by TamojitSaha** [sandeepmistry/arduino-nRF5#314]
@sandeepmistry  Please help me understand the pin mapping in terms of **P0.XX** to Arduino DigitalPin number. I cannot figure out how a digital pin number gets mapped to the pin-out of nrf51822.

For example,
 if I write `digitalWrite(13,HIGH)` in code, which GPIO(Pin name: **P0.??**) will have an output of 3.3V?

PS: I am using [this](https://raw.githubusercontent.com/wiki/RIOT-OS/RIOT/images/yunjia-nrf51822-full.jpg) board for development.

**Comment by sandeepmistry** [comment]
P0.13.
