### ISSUE TITLE
'pulseIn' was not declared in this scope

### ISSUE THREAD

**Issue by kenken64** [sandeepmistry/arduino-nRF5#317]
// defines pins numbers
const int trigPin = 11;
const int echoPin = 12;

// defines variables
long duration;
int distance;

void setup() {
  pinMode(trigPin, OUTPUT); // Sets the trigPin as an Output
  pinMode(echoPin, INPUT); // Sets the echoPin as an Input
  Serial.begin(9600); // Starts the serial communication
}
void loop() {
  // Clears the trigPin
  digitalWrite(trigPin, LOW);
  delayMicroseconds(2);
  // Sets the trigPin on HIGH state for 10 micro seconds
  digitalWrite(trigPin, HIGH);
  delayMicroseconds(10);
  digitalWrite(trigPin, LOW);
  // Reads the echoPin, returns the sound wave travel time in microseconds
  duration = pulseIn(echoPin, HIGH);
  // Calculating the distance
  distance= duration*0.034/2;
  // Prints the distance on the Serial Monitor
  Serial.print("Distance: ");
  Serial.println(distance);
}

**Comment by dlabun** [comment]
Please provide more information (environment, board, etc) if you would like help

**Comment by Mani90335** [comment]
is there any library to be included to sort out the error

**Comment by Mani90335** [comment]
i have found a solution to my error, i have written pulsein instead of pulseIn
changed it to capital( I )
