### ISSUE TITLE
Adafruit devices not supported - Also the latest Adafruit nRF52 Feather?

### ISSUE THREAD

**Issue by MagnusThome** [sandeepmistry/arduino-nRF5#321]
I didn't see the Adafruit Feather nRF52 Bluefruit in the list of non-supported devices so I thought I'd double check to make sure since it's quite different to their earlier BLE modules.

This is the one I'm wondering about: https://learn.adafruit.com/bluefruit-nrf52-feather-learning-guide/

Thanks!

**Comment by jeremypoulter** [comment]
Although it is not supported out of the box this can easily be added with a new veriant, however as Adafruit provide their own Arduino core you are probably better off using that one.

**Comment by dlabun** [comment]
Closing as question answered.
