### ISSUE TITLE
v0.7 Release

### ISSUE THREAD

**Issue by dlabun** [sandeepmistry/arduino-nRF5#323]
I am currently looking at doing a v0.7 release next weekend as the last release for this year. Currently there's only two items to be included:

-Fix for soft devices not installing (#312)
-Add support for DWM1001 board (#319)

There doesn't appear to be anything else ready to merge in.

**Comment by sandeepmistry** [comment]
@dlabun sounds good, #311 is looking close to being ready, but I don't think we should wait for it.

**Comment by Beetix** [comment]
Hi,

Is there any news on this release?

Thanks

**Comment by dlabun** [comment]
I could probably push out this release this weekend... Honestly nobody has been begging for it so I wasn't too worried about it.

**Comment by Beetix** [comment]
That would be great, thank you.

**Comment by Beetix** [comment]
Hi,

@dlabun Are you still planning on making the release?

Thanks

**Comment by sandeepmistry** [comment]
I’ll be making a new core release this weekend /cc @jhmaloney

**Comment by sandeepmistry** [comment]
The 0.7.0 release has been made!

https://github.com/sandeepmistry/arduino-nRF5/releases/tag/0.7.0
