### ISSUE TITLE
program nrf51822 with USB to TTL

### ISSUE THREAD

**Issue by ninanas98** [sandeepmistry/arduino-nRF5#326]
Hi,

So I want to program my nrf51822 beacon with an USB to TTL device but I get errors while uploading. Is it possible to use TTL to program the nrf51822 or do I have to get another driver?

Thanks in advance

**Comment by dlabun** [comment]
As stated before, with this project is only possible to program the nRF chip with either the JLINK, ST-LINK or BMP programmers. A USB to TTL adapter is not capable of programming the chip as you need a device that can communicate over the SWD port.
