### ISSUE TITLE
undefined reference to `analogWrite'

### ISSUE THREAD

**Issue by Benni77** [sandeepmistry/arduino-nRF5#341]
Hey guys,

tryin to use the analogWrite function but I always get the undefined reference error?! I don't really get the problem?!
Any Ideas?
Thanks :)

**Comment by dlabun** [comment]
Is this the first time your are trying to use this project? It does sound like your installation may be corrupt.

**Comment by Benni77** [comment]
Mh actually my whole projekt worked totally fine, till analogWrite came :D
I should try reinstalling that stuff. Maybe it's because I'm using some files from the adafruit Installation..

**Comment by Benni77** [comment]
Okay found a solution. I got the SparkFun nRF52832 Breakout Board.

I had to change the analog write functions name and comment out the analogwriteresolution in the library?!
Don't really know why but its working like this.

**Comment by dlabun** [comment]
You would have to check with Sparkfun as none of their board are currently supported by this project.
