### ISSUE TITLE
SPI1 dont work in Libraries?

### ISSUE THREAD

**Issue by schuppeste** [sandeepmistry/arduino-nRF5#343]
Hi,

i use Simple Codes to read bytes from SPI1 Device in Setup. It works.

If i copy the same 3 Lines to a Library Function the transfer Hangs, ready Libraries like SPIMemory for NRF52 has same effect.

`select();
    	SPI1.transfer(READ_STATUS_REGISTER);
	byte status = SPI1.transfer(0);
    	deselect();`

**Comment by dlabun** [comment]
This is not the appropriate place to ask for basic coding help.
