### ISSUE TITLE
Fix dead links in README

### ISSUE THREAD

**Issue by E3V3A** [sandeepmistry/arduino-nRF5#346]
Please update all the dead links in the README. 
(In particular those to Nordic Sem)

**Comment by dlabun** [comment]
Duplicate of issues listed in #312

**Comment by E3V3A** [comment]
@dlabun 
I wouldn't call that a duplicate, totally different issues and title.

I suggest to not link directly to the file themselves, but to the pages where the user can easily understand what files to download. If not, then perhaps just download yourself and add to this repo (unless they are huge). Kind of what the last commenter did in that issue.
