### ISSUE TITLE
Binary Integers not recongized

### ISSUE THREAD

**Issue by dlabun** [sandeepmistry/arduino-nRF5#35]
If you try to declare an integer in the binary format it will fail to compile... Verbose is attached, cheesy example sketch below.

`int Test = B001;

void setup() {
  // put your setup code here, to run once:

}

void loop() {
  // put your main code here, to run repeatedly:

}`
[zero.txt](https://github.com/sandeepmistry/arduino-nRF5/files/429214/zero.txt)
[nrf.txt](https://github.com/sandeepmistry/arduino-nRF5/files/429219/nrf.txt)

**Comment by sandeepmistry** [comment]
`cores/arduino/binary.h` does not match the SAMD core.

https://github.com/arduino/ArduinoCore-samd/blob/master/cores/arduino/binary.h

Would you mind trying to submit a pull request to make if the same as the SAMD core?

**Comment by dlabun** [comment]
That's a nifty little file... I'll take care of the pull request.

**Comment by sandeepmistry** [comment]
Fixed via #42.
