### ISSUE TITLE
Wrong pin defined for hackaBLE SPI SS?

### ISSUE THREAD

**Issue by henrygab** [sandeepmistry/arduino-nRF5#355]
https://github.com/sandeepmistry/arduino-nRF5/blob/acd234f3ec70cdbca9c725ef15ec2a63da8e3801/variants/hackaBLE/variant.h#L85-L87

Perhaps SS should not be the same as MOSI?

**Comment by dlabun** [comment]
Yes, that would an issue. It looks like SS is correct but the other SPI are wrong based on the schematic left in the variant file.
