### ISSUE TITLE
Selectable pin for Serial

### ISSUE THREAD

**Issue by Spycatcher2k** [sandeepmistry/arduino-nRF5#359]
Would it be possible to add the ability to choose the Serial pins, like I can in uPython? This would make using external serial devices so much easier to interface with.

**Comment by dlabun** [comment]
Do you mean selecting which hardware pins are used? That can already be done by changing the board files.

**Comment by Spycatcher2k** [comment]
Hi. Thanks for your reply. I was not aware I could do this. I'll have a try
shortly.

**Comment by Spycatcher2k** [comment]
Hi - can you give an example of this please - I can not find the section to change!

**Comment by dlabun** [comment]
Which board are you using? That way I can make it a little easier to understand.

**Comment by Spycatcher2k** [comment]
I'm using the BBC micro:bit. Thanks.

**Comment by dlabun** [comment]
So the file you would want to modify is this one:
https://github.com/sandeepmistry/arduino-nRF5/blob/master/variants/BBCmicrobit/variant.cpp

If you look down at line 53 and 54 of the file you'll see that currently pin P0.25 is the UART RX and P0.24 is the TX. If you change those two lines you can select another compatible pin for your serial port.

**Comment by Spycatcher2k** [comment]
Excellent! Thanks very much.

**Comment by dlabun** [comment]
Closing as resolved
