### ISSUE TITLE
nrf52 cpu frequency wrong in boards.txt definitions

### ISSUE THREAD

**Issue by monte-monte** [sandeepmistry/arduino-nRF5#366]
I'm not sure, whether this makes any difference at the end, but cpu frequency in board definitions is wrong for every nrf52 board. It is "build.f_cpu=16000000", which I believe means 16MHz, but that's the frequency of an nrf51 chip. However nrf52 has freq of 64Mhz.

**Comment by dlabun** [comment]
I believe it's just there for compatibility reasons for old AVR sketches that required a CPU frequency be specified. I think the SPI library was one place were CPU frequency was originally used but is no longer.
