### ISSUE TITLE
Getting MAC ID

### ISSUE THREAD

**Issue by kungfupizza** [sandeepmistry/arduino-nRF5#372]
Hi,
How can I get the MAC ID of my nRF52 using this core?

**Comment by dlabun** [comment]
There's no support for that in this core.

**Comment by kungfupizza** [comment]
Should this be added anytime sooner?
It'll be cool to have it.

**Comment by dlabun** [comment]
I don't know of any intent to add it, that's more a need for Bluetooth users which isn't the goal of this core.

**Comment by atc1441** [comment]
Hi this code will give you the Mac as a String:


```
  char tmp[16];
  sprintf(tmp, "%04X", NRF_FICR->DEVICEADDR[1] & 0xffff);
  String MyID = tmp;
  sprintf(tmp, "%08X", NRF_FICR->DEVICEADDR[0]);
  MyID += tmp;
```
