### ISSUE TITLE
Characteristic changes

### ISSUE THREAD

**Issue by utiq** [sandeepmistry/arduino-nRF5#374]
I started working with [this module](http://www.ebyte.com/en/product-view-news.aspx?id=243) using the Arduino IDE, so far I could blink leds and play around, somehting weird happens when I use the BLEPeripheral (0.4.0) library. This is my example code:

```
#include <SPI.h>
#include <BLEPeripheral.h>

const int ledPin = 7;

BLEPeripheral ledPeripheral = BLEPeripheral();

BLEService ledService = BLEService("19b10000e8f2537e4f6cd104768a1214");
BLECharCharacteristic ledCharacteristic = BLECharCharacteristic("19b10001e8f2537e4f6cd104768a1214", BLERead | BLEWrite);

void setup()
{
  Serial.begin(9600);
  pinMode(ledPin, OUTPUT);
  //digitalWrite(ledPin, HIGH);

  ledPeripheral.setAdvertisedServiceUuid(ledService.uuid());
  ledPeripheral.addAttribute(ledService);
  ledPeripheral.addAttribute(ledCharacteristic);
  ledPeripheral.setLocalName("Nordic NRF52 DK");
  ledPeripheral.setDeviceName("NRF52 example");
  ledPeripheral.begin();
}

void loop()
{
  BLECentral central = ledPeripheral.central();

  if (central) {
    while (central.connected()) {
      if (ledCharacteristic.written()) {
        Serial.println(ledCharacteristic.value());
        if (ledCharacteristic.value()) {
          digitalWrite(ledPin, HIGH);
        }
        else{
          digitalWrite(ledPin, LOW);
        }
      }
    }
  }
}
```
In the Bluetooth explorer the name shows correct, however, in the characteristics explorer it shows something totally different. It shows two characteristics named "Nordic Blinky Button" and "Nordic Blinky Led" with UUID 00001524-1212-EFDE-1523-785FEABCD123
I don't know if I should post this issue here or in [arduino-BLEPeripheral](https://github.com/sandeepmistry/arduino-BLEPeripheral)

**Comment by dlabun** [comment]
Please post in the arduino-BLEPeripheral project as this project doesn't provide any Bluetooth functionality
