### ISSUE TITLE
nrf51802

### ISSUE THREAD

**Issue by tcpipchip** [sandeepmistry/arduino-nRF5#377]
Sir,

I was using ZEPHYR to program the nrf51802. It´s works fine! 

But i would like to use ARDUINO, much better to developt.

Can you see if works Arduino with it ? If yes, wich board and softdevice to choose ?

Thank you!!!!!

**Comment by tcpipchip** [comment]
i had to go to zephyr!

**Comment by dlabun** [comment]
Closing, The readme answers all of these questions.
