### ISSUE TITLE
Need help with flashing sparkfun nrf52832 breakout

### ISSUE THREAD

**Issue by arihantdaga** [sandeepmistry/arduino-nRF5#379]
I knot that this is not exactly an issue with this repository, But i hoped to find someone who can help me here with programing sparkfun breakout board. 

I have connected stlink v2 with the conrtex debugger header of the sparkfun board. (attaching image). 
But everytime i try to upload, it throws error like this 
```
Open On-Chip Debugger 0.10.0-dev-gdc53227 (2016-04-09-13:45)
Licensed under GNU GPL v2
For bug reports, read
	http://openocd.org/doc/doxygen/bugs.html
debug_level: 2
0x4000
Info : The selected transport took over low-level target control. The results might differ compared to plain JTAG/SWD
adapter speed: 10000 kHz
Info : Unable to match requested speed 10000 kHz, using 4000 kHz
Info : Unable to match requested speed 10000 kHz, using 4000 kHz
Info : clock speed 4000 kHz
Error: open failed
in procedure 'program' 
in procedure 'init' called at file "embedded:startup.tcl", line 473
in procedure 'ocd_bouncer'
** OpenOCD init failed **
shutdown command invoked

the selected serial port 
 does not exist or your board is not connected

```

I have used this st link so many times to program other bluepill(stm32 based mcus). And i did the connections accordingly on this sparkfun board also. 
I am not sure if my st link is being detected by openocd or not. I tried to find on internet, but everything confused me even more. 

I'll be very happy, If anyone can please help me program this. 
<img width="687" alt="Screen Shot 2019-09-13 at 7 13 53 PM" src="https://user-images.githubusercontent.com/4976460/64867698-8730c880-d65b-11e9-90d3-d999494a8175.png">
<img width="591" alt="Screen Shot 2019-09-13 at 7 22 07 PM" src="https://user-images.githubusercontent.com/4976460/64867845-ce1ebe00-d65b-11e9-8017-46ac44955db8.png">
<img width="672" alt="Screen Shot 2019-09-13 at 7 21 51 PM" src="https://user-images.githubusercontent.com/4976460/64867846-ce1ebe00-d65b-11e9-9c27-a1398a079a4e.png">
<img width="591" alt="Screen Shot 2019-09-13 at 7 22 07 PM" src="https://user-images.githubusercontent.com/4976460/64867892-eabaf600-d65b-11e9-8c94-f9ad9eb63904.png">
<img width="672" alt="Screen Shot 2019-09-13 at 7 21 51 PM" src="https://user-images.githubusercontent.com/4976460/64867893-eb538c80-d65b-11e9-9602-027a832dec40.png">

**Comment by dlabun** [comment]
From looking at the verbose it's a communication issue with your programmer as the very last line states "the selected serial port does not exist or your board is not connected". You may want to verify you have the port selected.
