### ISSUE TITLE
Error while flashing SoftDevice

### ISSUE THREAD

**Issue by rahmanvm** [sandeepmistry/arduino-nRF5#387]
i am beginner.
can you help me to fix the problem

Open On-Chip Debugger 0.10.0-dev-00254-g696fc0a (2016-04-10-10:13)
Licensed under GNU GPL v2
For bug reports, read
	http://openocd.org/doc/doxygen/bugs.html
debug_level: 2
0
adapter speed: 10000 kHz
cortex_m reset_config sysresetreq
jaylink: Failed to open device: LIBUSB_ERROR_NOT_FOUND.
Info : No device selected, using first device.
Error: No J-Link device found.

Error while flashing SoftDevice.

**Comment by AliMalik5179** [comment]
Did u find a Solution to this problem?

**Comment by sandeepmistry** [comment]
Please see: https://github.com/sandeepmistry/arduino-nRF5/issues/412#issuecomment-715980363
