### ISSUE TITLE
Will this become the official core for the Arduino Primo ?

### ISSUE THREAD

**Issue by rogerclarkmelbourne** [sandeepmistry/arduino-nRF5#39]
I've just realised that the Arduino Primo will use the nRF52 as the main processor, and as Sandeep works for Arduino, I wondered if this repo will be the Core that the Primo uses, or whether Nordic are developing a separate core for the Repo.
In which case it seems pointless continuing with this one, as an official core written by Nordic developers would probably be better ??

**Comment by sabas1080** [comment]
Arduino Primo is of Arduino.org or not?

Sandeep works for Arduino.cc

**Comment by rogerclarkmelbourne** [comment]
Sorry. My mistake.

I will contact Arduino.org about this

**Comment by sandeepmistry** [comment]
This repo is maintained independently of either Arduino in my spare time. 

> In which case it seems pointless continuing with this one, as an official core written by Nordic developers would probably be better ??

I'm not sure what you mean't by "better" here. However, it's impossible to compare the quality of a project that is in the public domain to something that is not released.

I'm going to continue maintaining this version for my own use in either case.

**Comment by rogerclarkmelbourne** [comment]
Sorry

I was under the initial impression that Nordic were writing a core for Arduino.org

I have since contacted Arduino.org and have been informed that they are writing the core themselves with support from Nordic.
i.e its not Nordic who are writing the core.

It will be interesting to what Arduino.cc publish, as my understanding the nRF52 core will be released in a few weeks (1 or 2 weeks)
