### ISSUE TITLE
Arduino using thr nRF5 as BT via serial, like HC-05?

### ISSUE THREAD

**Issue by Flavio-da-Brescia** [sandeepmistry/arduino-nRF5#390]
First of all congratulations on the incredible work.
I have a question, im used to HC-05 where arduino uses serial to make use of BT.
Can the nRF5 be used in the same way? I need an Arduino Mega to have BT capability, no alternative. Can it use nRF5 via serial as BLE to commmunicate, for example, to a phone?
Thank you!

**Comment by dlabun** [comment]
Yes it’s possible but you’d need to write your own code on the nRF5 to handle the translation between the serial port and BLE.
