### ISSUE TITLE
Is there a way to request battery using this library?

### ISSUE THREAD

**Issue by AnthonyAchoy** [sandeepmistry/arduino-nRF5#396]
Hi, I've been working with a NRF522832 and your library and I'm trying to implement a solution that uses Services and Beaconing. I need to read the battery level remotely so I was wondering if there is a way to get battery level. I'm also trying to use the request battery that is in BLEPeripheral, but it is not working.

**Comment by vladkozlov69** [comment]
@AnthonyAchoy could you try this: https://gist.github.com/vladkozlov69/2500a27cd93245d71573164cda789539
