### ISSUE TITLE
FreeRTOS or multi-tasking equivalent?

### ISSUE THREAD

**Issue by marquesn** [sandeepmistry/arduino-nRF5#398]
Hello,

I've recently begun to use this repo with a nrf52832 on Arduino IDE. However, I can't find any multi-threading, multi-tasking, or scheduler libraries for the nRF5 on Arduino?

**Comment by jeremypoulter** [comment]
You should look at Adafruit's nRF52 BSP, that includes FreeRTOS. https://github.com/adafruit/Adafruit_nRF52_Arduino
