### ISSUE TITLE
Pairing refused with generic NRF51822 & Android phone

### ISSUE THREAD

**Issue by AlcorDust** [sandeepmistry/arduino-nRF5#403]
Hi, i successfully installed the software, i'm using ST-Link v2 and i'm able to upload sketches (i uploaded the simple blink and it works). Now i'm trying to use the bluetooth, but my phone (android) says that the device is refusing to pair. I'm using the BLEPeripheral library, and i tried all the example sketches. I'm using the S130 SoftDevice (s130_nrf51_2.0.1_softdevice.hex).

**Comment by sandeepmistry** [comment]
Please open an issue in the `BLEPeripheral` for this. This repo does not contain any BLE related functionality.
