### ISSUE TITLE
BLE example

### ISSUE THREAD

**Issue by nestorsilk** [sandeepmistry/arduino-nRF5#41]
Arduino-nRF5 works very well for me. Using it with a nrf52 development kit. Succeeded also in changing the path structure within the platform.txt to map the sdk structure.  But when trying to start BLE examples I ran into a lot of troubles as it is difficult to find out which SDK 11 files are really necessary to run within the Arduino environment.

Therefore I wanted to ask whether someone already succeeded to implement a BLE example with Arduino-nRF5 for the nRF52832 MCU?

Tom

**Comment by sabas1080** [comment]
Hi

I am using library BLE Peripheral branch nRF5
https://github.com/sandeepmistry/arduino-BLEPeripheral/tree/nRF5

for development in nRF51 and examples work

**Comment by nestorsilk** [comment]
Thank you very much. Was not aware of the existence of this library. Works like a charm. Excellent!

**Comment by sandeepmistry** [comment]
@sabas1080 thanks for helping out!

I've added a section for BLE in the read me (https://github.com/sandeepmistry/arduino-nRF5#ble).

Also, the `BLEPeripheral` nRF5 branch has been merged to master, and a new v0.3.0 version should be available in the Arduino IDE library manager in the next hour or so.
