### ISSUE TITLE
Invalid port mapping in pulse.c pulseIn

### ISSUE THREAD

**Issue by sanyi** [sandeepmistry/arduino-nRF5#420]
I tried to use a distance sensor on BBC:microbit PIN2. `uint32_t pulseIn(uint32_t pin, uint32_t state, uint32_t timeout)` failed to work correctly. I realized in `NRF_GPIO->IN` PIN2 modifies bit 1 not bit 2 as L:36 implies.

Modifying L:36 `uint32_t bit = 1 << pin; //p.ulPin;` to `uint32_t bit = 1 << pin - 1; //p.ulPin;` fixes the thing and enables the desired functionality.

**Comment by sandeepmistry** [comment]
Should be addressed as part of https://github.com/sandeepmistry/arduino-nRF5/pull/439.
