### ISSUE TITLE
Support for micro:bit v2

### ISSUE THREAD

**Issue by jhmaloney** [sandeepmistry/arduino-nRF5#430]
Do you plan to add support for the new micro:bit (https://microbit.org/new-microbit/)? That uses the nrf52833 chip and it also needs to access pins above pin 31, so a few library changes are needed. If you are interested, I can do PR with the changes I made, although someone should check my changes and also look for additional places that might require the same fix to handle high-numbered pins.

**Comment by sandeepmistry** [comment]
Hi @jhmaloney,

No formal plans to add support at this time, however I would be more than happy to review a pull request for this.

cc/ @jaustin

**Comment by jhmaloney** [comment]
Great! Besides creating a new variant, I found that a few libraries needed to be extended to handle port B pin numbers (i.e. pin numbers > 31). I will put together what I have so far and issue a PR and you can see what you think. As far as I know, this is still the primary Arduino framework for the micro:bit, so it would be great to make it work with the micro:bit v2.. (Adafruit has a framework for their own nrf5x boards.)

**Comment by jhmaloney** [comment]
Submitted PR #432, BBC microbit v2

**Comment by sandeepmistry** [comment]
I've updated the nRF MDK and opened a new PR based on @jhmaloney's work: https://github.com/sandeepmistry/arduino-nRF5/pull/439

**Comment by sandeepmistry** [comment]
This is in with PR https://github.com/sandeepmistry/arduino-nRF5/pull/439 now!
