### ISSUE TITLE
compiling error : nrf_delay.h: No such file or directory

### ISSUE THREAD

**Issue by zoujixing** [sandeepmistry/arduino-nRF5#44]
This error appears on version 0.2.0, compiling successfully on version 0.1.0.

**Comment by sandeepmistry** [comment]
Hi @zoujixing,

Things seem fine on my Mac and I've also setup Travis CI to build for Linux: https://travis-ci.org/sandeepmistry/arduino-nRF5

What OS are you using? Also, could you please share verbose build output from the IDE.

**Comment by d00616** [comment]
I had this issue to. After upgrading Arduino to 1.6.12 this problem was solved.

**Comment by sandeepmistry** [comment]
@d00616 thanks for the tip!

I'm closing this for now, as it appears to be an Arduino IDE issue, that has been resolved with a later Arduino IDE release.
