### ISSUE TITLE
Missing SDK BLE libraries etc

### ISSUE THREAD

**Issue by rogerclarkmelbourne** [sandeepmistry/arduino-nRF5#46]
What is the best method to use Nordic's BLE libraries?

i.e I tried to compile the ble_peripheral\ble_app_beacon example from SDK V11, but none of the headers are in your repo.

Is this a licensing issue?

**Comment by sandeepmistry** [comment]
I've never really used the Nordic BLE libraries with Arduino (or anything), instead just use the soft device directly. I suggest you look at: https://github.com/sandeepmistry/arduino-nRF5#ble

However, looking at SDK 12 headers the license is very restrictive:
```
/* Copyright (c) 2015 Nordic Semiconductor. All Rights Reserved.
 *
 * The information contained herein is property of Nordic Semiconductor ASA.
 * Terms and conditions of usage are described in detail in NORDIC
 * SEMICONDUCTOR STANDARD SOFTWARE LICENSE AGREEMENT.
 *
 * Licensees are granted free, non-transferable use of the information. NO
 * WARRANTY of ANY KIND is provided. This heading must NOT be removed from
 * the file.
 */
```
