### ISSUE TITLE
How i can dev in NRF52810?

### ISSUE THREAD

**Issue by vanhcm20** [sandeepmistry/arduino-nRF5#473]
I have a NRF52810 chip (not SoC or devkit), how i can dev it.
What board will be selected?
P0.1(chip) is what pin in Arduino.

**Comment by samlbakr** [comment]
Did you ever solve this?

**Comment by vanhcm20** [comment]
@samlbakr i dont get it, my jtag is bootleg and i cant up find out the way to upload it
