### ISSUE TITLE
arm-none-eabi-g++: no such file or directory

### ISSUE THREAD

**Issue by krisstakos** [sandeepmistry/arduino-nRF5#496]
Any help on that? 
I'm using Pop_os with Arduino IDE V2 every other third party board compiles fine but not the nrfXXX family from that repo
I've checked all the paths and binaries that are used in that particular command below, everything is there and the permissions are also fine. Honestly I'm out of ideas what can be wrong. Manually running that same command in the terminal seems to be fine. So I still think is something related to permissions but not sure exactly where

>/home/kristian/.arduino15/packages/sandeepmistry/tools/gcc-arm-none-eabi/5_2-2015q4/bin/arm-none-eabi-g++ -mcpu=cortex-m4 -mthumb -c -g -Os -w -mfloat-abi=hard -mfpu=fpv4-sp-d16 -std=gnu++11 -ffunction-sections -fdata-sections -fno-threadsafe-statics -nostdlib --param max-inline-insns-single=500 -fno-rtti -fno-exceptions -w -x c++ -E -CC -DF_CPU=16000000 -DARDUINO=10607 -DARDUINO_GENERIC -DARDUINO_ARCH_NRF5 -DNRF52 -DS132 -DNRF51_S132 -DNRF5 -I/home/kristian/.arduino15/packages/sandeepmistry/hardware/nRF5/0.7.0/cores/nRF5/SDK/components/toolchain/ -I/home/kristian/.arduino15/packages/sandeepmistry/hardware/nRF5/0.7.0/cores/nRF5/SDK/components/toolchain/CMSIS/Include -I/home/kristian/.arduino15/packages/sandeepmistry/hardware/nRF5/0.7.0/cores/nRF5/SDK/components/toolchain/gcc/ -I/home/kristian/.arduino15/packages/sandeepmistry/hardware/nRF5/0.7.0/cores/nRF5/SDK/components/device/ -I/home/kristian/.arduino15/packages/sandeepmistry/hardware/nRF5/0.7.0/cores/nRF5/SDK/components/drivers_nrf/delay/ -I/home/kristian/.arduino15/packages/sandeepmistry/hardware/nRF5/0.7.0/cores/nRF5/SDK/components/softdevice/s132/headers/ -DUSE_LFXO -I/home/kristian/.arduino15/packages/sandeepmistry/hardware/nRF5/0.7.0/cores/nRF5 -I/home/kristian/.arduino15/packages/sandeepmistry/hardware/nRF5/0.7.0/variants/Generic /home/kristian/.var/app/cc.arduino.IDE2/cache/arduino-sketch-9D5DCD9A036A479F1A2A6A3149FF771D/sketch/sketch_nov1a.ino.cpp -o /dev/null

> fork/exec /home/kristian/.arduino15/packages/sandeepmistry/tools/gcc-arm-none-eabi/5_2-2015q4/bin/arm-none-eabi-g++: no such file or directory

>Compilation error: fork/exec /home/kristian/.arduino15/packages/sandeepmistry/tools/gcc-arm-none-eabi/5_2-2015q4/bin/arm-none-eabi-g++: no such file or directory`

EDIT: I've tried re-installing the nrf52 core multiple times, also wiped arduino IDE couple of times

**Comment by krisstakos** [comment]
nvm tried win10 64-bit - worked, also ubuntu-22.04 - worked
So I was using the version from the AppStore, switching to AppImage from the official arduino website solved my issues

**Comment by bkdevel** [comment]
I have the same issue on OpenSUSE TW
