### ISSUE TITLE
printf support

### ISSUE THREAD

**Issue by d00616** [sandeepmistry/arduino-nRF5#51]
At the moment i play around with printf. This doesn't work until i have modified Print.cpp like https://forum.arduino.cc/index.php?topic=197601.msg1488213#msg1488213

I think this is not a perfect solution because file is ignored. I have no idea about a correct implementation.

```
diff --git a/cores/nRF5/Print.cpp b/cores/nRF5/Print.cpp
index 05a1f18..71f7551 100644
--- a/cores/nRF5/Print.cpp
+++ b/cores/nRF5/Print.cpp
@@ -37,6 +37,16 @@ size_t Print::write(const uint8_t *buffer, size_t size)
   return n;
 }
 
+// for printf compatibility
+extern "C" {
+__attribute__((weak))
+int _write(int file, char *buffer, int size)
+{
+  Serial.write(buffer, size);
+       return 0;
+}
+}
+
 size_t Print::print(const __FlashStringHelper *ifsh)
 {
   return print(reinterpret_cast<const char *>(ifsh));

```

**Comment by sandeepmistry** [comment]
Hi @d00616,

> This doesn't work until i have modified Print.cpp like

I think this is fine, it's the same behaviour as the official Arduino SAMD core. Also, `printf` is not really "Arduino" style.

> I think this is not a perfect solution because file is ignored.

What do you mean by this?

**Comment by sandeepmistry** [comment]
Closing for now due to lack of activity.

**Comment by d00616** [comment]
Is a pull request with this solution welcome?

**Comment by sandeepmistry** [comment]
Not at this time, the current goal is to track the official SAMD core. It requires the same workaround to make `printf` functional.
