### ISSUE TITLE
Bluetooth Mesh

### ISSUE THREAD

**Issue by danlsk** [sandeepmistry/arduino-nRF5#62]
Will this core development roadmap include the Bluetooth Mesh at some point? Currently, there is Nordic Open Mesh for N51/N52. Will this be more immediate one?

**Comment by sandeepmistry** [comment]
No plans to include this. My preference would be to have this as an external Arduino Library that is installable via the Arduino IDE Library manager. This would make it possible to also use with other nRF51/52 Arduino cores.

**Comment by probonopd** [comment]
Seems to be implemented in S140,S132, S130 and S110 SoftDevices

Source:
https://www.nordicsemi.com/eng/Products/Bluetooth-low-energy/nRF5-SDK-for-Mesh

**Comment by probonopd** [comment]
https://github.com/NordicPlayground/nRF51-ble-bcast-mesh is talking about Mesh and Arduino. Usable for our purpose?
