### ISSUE TITLE
How to flash Plain nRF52 MCU

### ISSUE THREAD

**Issue by TraxXavier** [sandeepmistry/arduino-nRF5#73]
I got a coupe of http://www.ebay.at/itm/322332640473?_trksid=p2060353.m2749.l2649&ssPageName=STRK%3AMEBIDX%3AIT

Now i wonder how to program them?
There is no entry "Plain nRF52 MCU" in the board menu i can only select "nRF52 DK" does that also work with generic nRF52 IC's?

Also what programmer should I get? I need this Tag-Connect interface which of the 3 listed supports that: J-Link, ST-Link V2, or CMSIS-DAP ?

**Comment by sandeepmistry** [comment]
@TraxXavier if you follow https://github.com/sandeepmistry/arduino-nRF5#from-git-for-core-development - you will see a Generic nRF52 type.

> Also what programmer should I get? I need this Tag-Connect interface which of the 3 listed supports that: J-Link, ST-Link V2, or CMSIS-DAP ?

Any of those programmer types will work.
