### ISSUE TITLE
Where to find examples on how to use BT-LE on the nRF52 chip?

### ISSUE THREAD

**Issue by TraxXavier** [sandeepmistry/arduino-nRF5#82]
Where can I find some examples how to get BT-LE to operate on the nRF52?

I would need something as a starting point to be able to read some data out on an android phone

Could anyone please point me to some sample code I could start with?

Thanks
Trax

**Comment by dlabun** [comment]
Quoting the readme file:

This Arduino Core does not contain any Arduino style API's for BLE functionality. All the relevant Nordic SoftDevice (S110, S130, S132) header files are included build path when a SoftDevice is selected via the Tools menu.

Recommend BLE Libraries

BLEPeripheral
v0.3.0 and greater, available via the Arduino IDE's library manager.
Supports peripheral mode only.

**Comment by TraxXavier** [comment]
Ok this: https://github.com/sandeepmistry/arduino-BLEPeripheral ?
but it does not mentions nRF52 is it compatible with it anyways?

**Comment by TraxXavier** [comment]
the lib seams to work fine thanks
