### ISSUE TITLE
millis errors

### ISSUE THREAD

**Issue by austin1611** [sandeepmistry/arduino-nRF5#86]
The code in delay.c has some errors:

1) the RTC1 (at least on nRF52) is a 24bit counter. So line 33 and 40 in delay.c should have a 24 bit shift, not a 32 bit shift:
```
uint64_t ticks = (uint64_t)((uint64_t)overflows << (uint64_t)24) | (uint64_t)(NRF_RTC1->COUNTER);
uint64_t ticks = (uint64_t)((uint64_t)overflows << (uint64_t)24) | (uint64_t)(NRF_RTC1->COUNTER);
```

2) The `RTC1_IRQHandler()` never gets called because the core doesn't enable this interrupt by default. Can be solved with:  `NRF_RTC1->INTENSET = 2` 

Without these changes, both `millis()` and `micros()` will be reset to 0 after 5.1 minutes instead of 49 days

**Comment by sandeepmistry** [comment]
Closed via #87.
