### ISSUE TITLE
Sending bytes to Serial stops working

### ISSUE THREAD

**Issue by prjh** [sandeepmistry/arduino-nRF5#9]
Sending bytes, e,g, via the Arduino Serial Monitor does halt the loop. May be the receive buffer is not yet initialized correctly. The standard Arduino `Communication - SerialEvent` example can be used for reproducing this issue.

**Comment by bojh** [comment]
I have tested the new commit (eb01946) with removed "driver_nrf//hal" on nRF52-DK. The described issue is still there.

**Comment by sandeepmistry** [comment]
This should be fixed by 9872aaa34e89809885e7c66f13670122e1829f9a.

I think the nRF51 .S file was being used on nRF52.

**Comment by bojh** [comment]
@sandeepmistry thank's I can confirm - It's working now. That `serialEvent` callback is not supported yet, is not a blocker.
